// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwkMCIu44aMJtQ__W-O-wXV5vQhgGnGM8',
    appId: '1:357697009843:web:f2dfcc3a5348b2fdd718c6',
    messagingSenderId: '357697009843',
    projectId: 'simplio-io',
    authDomain: 'simplio-io.firebaseapp.com',
    storageBucket: 'simplio-io.appspot.com',
    measurementId: 'G-BWGX40J8J8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYQ1B_zhV84S00bbDRbdtDUM0AxV8a8Lk',
    appId: '1:357697009843:android:49c811e89284c16ad718c6',
    messagingSenderId: '357697009843',
    projectId: 'simplio-io',
    storageBucket: 'simplio-io.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwHYbByxCQg64KsqnW2eQ4SEZsvQqEM_U',
    appId: '1:357697009843:ios:d04087bcd45c7fccd718c6',
    messagingSenderId: '357697009843',
    projectId: 'simplio-io',
    storageBucket: 'simplio-io.appspot.com',
    iosClientId: '357697009843-i6pggqmp1lchik8pm5lvc5ftl15c2bhd.apps.googleusercontent.com',
    iosBundleId: 'dev.simplio.app',
  );
}
