platform :ios do
 desc "Load ASC API Key information to use in subsequent lanes"
 lane :load_asc_api_key do
   app_store_connect_api_key(
     key_id: "1580713368",
     issuer_id: "tinh.pham@simplio.io",
     key_content: ENV["ASC_KEY"],
#      key_id: ENV["ASC_KEY_ID"],
#      issuer_id: ENV["ASC_ISSUER_ID"],
#      key_content: ENV["ASC_KEY"],
     in_house: false # detecting this via ASC private key not currently supported
   )
 end
end
