name: Increase application version
env:
  FLUTTER_VERSION: '2.10.2'

on:
  workflow_call:

jobs:
  set-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Run read-yaml action
        id: yaml-data
        uses: KJ002/read-yaml@main
        with:
          file: './pubspec.yaml'
          key-path: '["version"]'

      - name: Get parsed version
        run: |
          IFS='.'
          read -ra parsed_versions <<< "${{ steps.yaml-data.outputs.data }}"
          echo "MAJOR=${parsed_versions[0]}" >> $GITHUB_ENV
          echo "MINOR=${parsed_versions[1]}" >> $GITHUB_ENV
          patch_build=$(echo ${parsed_versions[2]} | tr "+" "\n")
          read -ra temp <<< "$patch_build"
          echo "PATCH=${temp[0]}" >> $GITHUB_ENV

      - name: Write version to the version.yml
        run: |
          echo "---" > ./version.yml
          echo "major: ${{ env.MAJOR }}" >> ./version.yml
          echo "minor: ${{ env.MINOR }}" >> ./version.yml
          echo "patch: ${{ env.PATCH }}" >> ./version.yml

#      - uses: actions/upload-artifact@master
#        with:
#          name: version-file
#          path: ./version.yml

      - name: Run Fastlane
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: increase_patch_version
          subdirectory: ios
          env: ${{ inputs.environment }}
      - name: Commit the change
        run: |
          git checkout ${{ env.BRANCH }}
          git add pubspec.yaml
          git config --global user.name 'Jan Vraštil'
          git config --global user.email '${{ secrets.GIT_EMAIL }}'
          git remote set-url origin https://x-access-token:${{ secrets.GIT_AUTHORIZATION }}@github.com/SimplioOfficial/simplio-app
          git commit -m "[automated commit] Version increase"
          git push

#  pokus:
#    needs: set-version
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/download-artifact@master
#        with:
#          name: version-file
#          path: ./
#      - name: Display folders
#        run: ls -la
#      - name: Display version.yml
#        run: tail ./version.yml
