name: Run tests
env:
  FLUTTER_VERSION: '3.0.2'

on:
  workflow_call:
    inputs:
      e2e:
        description: 'Boolean value which trigger running e2e tests'
        default: true
        required: true
        type: boolean
jobs:
  analyze-app:
    runs-on: ubuntu-latest
    name: Analyze application
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VERSION
      - run: flutter pub get
      - name: Analyze files
        run: flutter analyze .

  tests:
    runs-on: ubuntu-latest
    name: Unit tests
    needs: analyze-app
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VERSION
      - run: flutter pub get
      - run: flutter test

  run-e2e-tests:
    if: ${{ inputs.e2e }}
    runs-on: ubuntu-latest
    name: e2e tests
    needs: analyze-app
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VERSION
      - run: flutter pub get
  #      TODO
  #      - run: flutter test