name: Deploy Flutter Mobile Beta
env:
  FLUTTER_VERSION: '2.10.2'

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
#on:
#  push:
#    # This is the branch where this work flow is triggered
#    branches:
#      - beta/*

# NOTE: The following jobs won't include Flutter-specific tasks such as running lint checks, tests.
# This is expected because the goal of this workflow is to "deploy" apps.
# Prior checks should be done on a separate workflow file.
jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run unit tests
    steps:
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VERSION
      - run: flutter pub get
      - run: flutter test

  build-ios:
    needs: run-tests
    name: Build ios
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VERSION
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - name: Run Fastlane
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: beta
          subdirectory: ios
        env:
          APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
          DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
          DEVELOPER_APP_IDENTIFIER: '${{ secrets.DEVELOPER_APP_IDENTIFIER }}'
          DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
          FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
          GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
          PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
          TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
          TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'

  build-android:
    needs: run-tests
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VERSION
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
      - name: Run Fastlane
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: beta
          subdirectory: android
