name: Deploy Flutter Mobile Beta

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
#on:
#  push:
#    # This is the branch where this work flow is triggered
#    branches:
#      - beta/*

# NOTE: The following jobs won't include Flutter-specific tasks such as running lint checks, tests.
# This is expected because the goal of this workflow is to "deploy" apps.
# Prior checks should be done on a separate workflow file.
jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.2'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk
      - run: flutter build appbundle
#  deploy_apk:
#    name: Deploy Flutter (Google Play Beta)
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code from ref
#        uses: actions/checkout@v2
#        with:
#          ref: ${{ github.ref }}
#      - name: Setup Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: 12.x
#      # This decrypts secrets such as your keystore, Google Play Service account JSON key
##      - name: Decrypt keys
##        run: ./.github/scripts/decrypt_android_secrets.sh
##        env:
##          ANDROID_SECRETS_PASSPHRASE: ${{ secrets.ANDROID_SECRETS_PASSPHRASE }}
#      - name: Run Flutter tasks
#        uses: subosito/flutter-action@v1
#        with:
#          channel: 1.17.5
#      - run: flutter pub get
#      - run: flutter pub run build_runner build
#      - run: flutter build appbundle
#      - name: Run Fastlane
#        uses: maierj/fastlane-action@v1.4.0
#        with:
#          lane: beta
#          subdirectory: android
#  deploy_ios:
#    name: Deploy Flutter (TestFlight Beta Testers)
#    runs-on: macOS-latest
#    steps:
#      - name: Checkout code from ref
#        uses: actions/checkout@v2
#        with:
#          ref: ${{ github.ref }}
#      - name: Setup Java
#        uses: actions/setup-java@v1
#        with:
#          java-version: 12.x
##      - uses: webfactory/ssh-agent@v0.4.0
##        with:
##          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#      - name: Run Flutter tasks
#        uses: subosito/flutter-action@v1
#        with:
#          channel: 1.17.5
#      - run: flutter pub get
#      - run: flutter pub run build_runner build
#      - run: flutter build ios --release --no-codesign
#      - name: Run fastlane
#        uses: maierj/fastlane-action@v1.4.0
#        with:
#          lane: beta
#          subdirectory: ios
#        env:
#          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
#          MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
#          GH_ACCESS_TOKEN: '${{ secrets.GH_ACCESS_TOKEN }}'
#          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
#  create_pre_release:
#    name: Create Github Pre-release
#    needs: [deploy_apk, deploy_ios]
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code from ref
#        uses: actions/checkout@v2
#        with:
#          ref: ${{ github.ref }}
#          fetch-depth: 0
#      - name: Prepare changelog output
#        uses: scottbrenner/generate-changelog-action@master
#        id: release_changelog
#        env:
#          REPO: ${{ github.repository }}
#      - name: Create release
#        uses: actions/create-release@latest
#        id: create_beta_release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: ${{ github.ref }}
#          release_name: Release ${{ github.ref }}
#          body: |
#            ${{ steps.Changelog.outputs.changelog }}
#          draft: false
#          prerelease: true
