name: Appium CI

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest # the machine type
    strategy: 
      matrix:
        api-level: [25] #Google api level for example [25,23,28] 
        target: [default]
    steps:
    - uses: actions/checkout@v2 #checkout the code 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install and Run Appium Server
      run: |
        chmod +x ./.github/scripts/RunAppiumServer.sh 
        ./.github/scripts/RunAppiumServer.sh
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v1 # install and create the Emulator
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew test/functional/appium_dart_android_test.dart --info # running our test with info to check the results