name: Deploy test version of Simplio app v2 to AppStore and GooglePlay

on:
  pull_request:
#  push:
#    tags:
#      - 'v*'

jobs:
  run-tests:
    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@task/11-setup_basic_ci_cd_pipelines
    with:
      e2e: true

  increase-version:
    needs: [run-tests]
    uses: SimplioOfficial/simplio-app/.github/workflows/_increase_version.yml@subtask/11-automatic_version_increase

  pokus:
    needs: [increase-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
#      - uses: actions/download-artifact@master
#        with:
#          name: version-file
#          path: ./
#      - name: Display folders
#        run: ls -la
      - name: Display version.yml
        run: head -n 20 ./pubspec.yaml

#  build-ios:
#    needs: [run-tests, increase-version]
#    uses: SimplioOfficial/simplio-app/.github/workflows/_publish_ios.yml@task/11-setup_basic_ci_cd_pipelines
#    with:
#      environment: 'dev'
#    secrets:
#      APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
#      DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
#      DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
#      FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
#      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
#      MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
#      GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
#      PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
#      TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
#      TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
#
#  build-android:
#    needs: [run-tests, increase-version]
#    uses: SimplioOfficial/simplio-app/.github/workflows/_publish_android.yml@task/11-setup_basic_ci_cd_pipelines
#    secrets:
#      ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
#    with:
#      environment: 'dev'
