name: Deploy test version of Simplio app v2 to AppStore and GooglePlay

on:
  push:
    tags:
      - 'v*'
    branches-ignore:
      - 'master'

jobs:
  increase-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
      - name: Write version to the version.yml
        run: |
          echo "---" > ./version.yml
          echo "major: 1" >> ./version.yml
          echo "minor: 0" >> ./version.yml
          echo "patch: 5" >> ./version.yml
      - name: Display version.yml
        run: tail ./version.yml
      - name: Commit the change
        run: |
          git add -A
          git config --global user.name 'Jan Vraštil'
          git config --global user.email '${{ secrets.GIT_EMAIL }}'
          git remote set-url origin https://x-access-token:${{ secrets.GIT_AUTHORIZATION }}@github.com/SimplioOfficial/simplio-app
          git commit -m "[automated commit] Version increase"
          git push

#  run-tests:
#    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@task/11-setup_basic_ci_cd_pipelines
#    if: github.event.review.state == 'approved'
#    with:
#      e2e: true
#
#  build-ios:
#    needs: [run-tests]
#    uses: SimplioOfficial/simplio-app/.github/workflows/_publish_ios.yml@task/11-setup_basic_ci_cd_pipelines
#    with:
#      environment: 'dev'
#    secrets:
#      APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
#      DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
#      DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
#      FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
#      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
#      MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
#      GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
#      PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
#      TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
#      TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
#
#  build-android:
#    needs: [run-tests]
#    uses: SimplioOfficial/simplio-app/.github/workflows/_publish_android.yml@task/11-setup_basic_ci_cd_pipelines
#    secrets:
#      ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
#    with:
#      environment: 'dev'
