name: Deploy test version of Simplio app v2 to AppStore and GooglePlay

on:
  pull_request:
#  push:
#    tags:
#      - 'v*'

jobs:
  set-version:
#    if: github.event.base_ref != 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
#        with:
#          ref: ${{ github.event.release.target_commitish }}
#          ${{ github.event.pull_request.head.sha }}
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Run read-yaml action
        id: yaml-data
        uses: KJ002/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './pubspec.yaml'          # File to read from
          key-path: '["version"]' # Access the runs key then the using key and retuns the value.

      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"

      - name: Branch name
        run : echo ${{ github.event.release.tag_name }}
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          prefix='v'
          tag_version=${RELEASE_VERSION#$prefix}; #Remove prefix
          IFS='.'     # hyphen (.) is set as delimiter
          read -ra parsed_versions <<< "$tag_version"
          echo "MAJOR=${parsed_versions[0]}" >> $GITHUB_ENV
          echo "MINOR=${parsed_versions[1]}" >> $GITHUB_ENV
          echo "PATCH=${parsed_versions[2]}" >> $GITHUB_ENV

      - name: Write version to the version.yml
        run: |
          echo "---" > ./version.yml
          echo "major: ${{ env.MAJOR }}" >> ./version.yml
          echo "minor: ${{ env.MINOR }}" >> ./version.yml
          echo "patch: ${{ env.PATCH }}" >> ./version.yml
      - name: Display version.yml
        run: tail ./version.yml
      - uses: actions/upload-artifact@master
        with:
          name: version-file
          path: ./version.yml
#      - name: Display target branch
#        run: echo ${{ github.event.release.target_commitish }}
#      - name: Commit the change
#        run: |
#          git branch
##          git checkout '${{ github.event.release.target_commitish }}'
#          git add -A
#          git config --global user.name 'Jan Vraštil'
#          git config --global user.email '${{ secrets.GIT_EMAIL }}'
#          git remote set-url origin https://x-access-token:${{ secrets.GIT_AUTHORIZATION }}@github.com/SimplioOfficial/simplio-app
#          git commit -m "[automated commit] Version increase"
#          git push

  pokus:
    needs: set-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: version-file
          path: ./
      - name: Display folders
        run: ls -la
      - name: Display version.yml
        run: tail ./version.yml

#  run-tests:
#    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@task/11-setup_basic_ci_cd_pipelines
##    if: github.event.review.state == 'approved'
#    with:
#      e2e: true

#  build-ios:
#    needs: [run-tests, set-version]
#    uses: SimplioOfficial/simplio-app/.github/workflows/_publish_ios.yml@task/11-setup_basic_ci_cd_pipelines
#    with:
#      environment: 'dev'
#    secrets:
#      APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
#      DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
#      DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
#      FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
#      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
#      MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
#      GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
#      PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
#      TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
#      TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'
#
#  build-android:
#    needs: [run-tests, set-version]
#    uses: SimplioOfficial/simplio-app/.github/workflows/_publish_android.yml@task/11-setup_basic_ci_cd_pipelines
#    secrets:
#      ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
#    with:
#      environment: 'dev'
