name: Deploy test version of Simplio app v2 to AppStore and GooglePlay

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'master'
      - '*'

jobs:
  run-tests:
    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@subtask/11-automatic_version_increase
    with:
      e2e: true

  set-version:
    needs: [run-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Get version from tag
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}
          prefix='v'
          tag_version=${RELEASE_VERSION#$prefix};
          IFS='.'
          read -ra parsed_versions <<< "$tag_version"
          echo "RELEASE_VERSIONS=$parsed_versions" >> $GITHUB_ENV

      - name: Set versions
        run: |
          echo '::set-output name=MAJOR::${parsed_versions[0]}'
          echo '::set-output name=MINOR::${parsed_versions[1]}'
          echo '::set-output name=PATCH::${parsed_versions[2]}'
        id: output-data
#          echo "MAJOR=${parsed_versions[0]}" >> $GITHUB_ENV
#          echo "MINOR=${parsed_versions[1]}" >> $GITHUB_ENV
#          echo "PATCH=${parsed_versions[2]}" >> $GITHUB_ENV

  build-ios:
    needs: [set-version]
    uses: SimplioOfficial/simplio-app/.github/workflows/_publish_ios.yml@subtask/11-automatic_version_increase
    with:
      environment: 'production'
      major: '${{ steps.output-data.outputs.MAJOR }}'
      minor: '${{ steps.output-data.outputs.MINOR }}'
      patch: '${{ steps.output-data.outputs.PATCH }}'
    secrets:
      APP_STORE_CONNECT_TEAM_ID: '${{ secrets.APP_STORE_CONNECT_TEAM_ID }}'
      DEVELOPER_APP_ID: '${{ secrets.DEVELOPER_APP_ID }}'
      DEVELOPER_PORTAL_TEAM_ID: '${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}'
      FASTLANE_APPLE_ID: '${{ secrets.FASTLANE_APPLE_ID }}'
      FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: '${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}'
      MATCH_PASSWORD: '${{ secrets.MATCH_PASSWORD }}'
      GIT_AUTHORIZATION: '${{ secrets.GIT_AUTHORIZATION }}'
      PROVISIONING_PROFILE_SPECIFIER: '${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}'
      TEMP_KEYCHAIN_PASSWORD: '${{ secrets.TEMP_KEYCHAIN_PASSWORD }}'
      TEMP_KEYCHAIN_USER: '${{ secrets.TEMP_KEYCHAIN_USER }}'

#  build-android:
#    needs: [set-version]
#    uses: SimplioOfficial/simplio-app/.github/workflows/_publish_android.yml@subtask/11-automatic_version_increase
#    secrets:
#      ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
#    with:
#      environment: 'production'
#      major: ${{ env.MAJOR }}
#      minor: ${{ env.MINOR }}
#      patch: ${{ env.PATCH }}
#
