name: Publish Android
env:
  FLUTTER_VERSION: '2.10.2'

on:
  workflow_call:
    inputs:
      fastlane-name:
        description: 'String value that determines if production or dev packages are built'
        default: 'dev'
        required: true
        type: string

jobs:
  build-android:
    runs-on: ubuntu-latest
    needs: [ run-tests ]
    name: Build Android
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Decrypt Android keys
        run: sh ./.github/scripts/decrypt_android_secrets.sh
        env:
          ANDROID_KEYS_SECRET_PASSPHRASE: ${{ secrets.ANDROID_KEYS_SECRET_PASSPHRASE }}
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: $FLUTTER_VERSION
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Build app
        run: flutter build apk --release
      - name: Run Fastlane
        uses: maierj/fastlane-action@v2.2.0
        with:
          lane: ${{ inputs.fastlane-name }}
          subdirectory: android
