name:  Run Integration Tests

env:
  FLUTTER_VERSION: '2.10.2'

on:
  workflow_call:
    inputs:
      e2e:
        description: 'Boolean value which trigger running e2e tests'
        default: true
        required: true
        type: boolean
  workflow_dispatch:

jobs:

  test:
    runs-on: macos-latest
    #sequence of tasks called
    steps:
      - uses: actions/checkout@v2
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - run: flutter pub get


  drive_ios:
    strategy:
      matrix:
        device:
          - "iPhone 13 Pro Simulator"
          - "iPhone 11 Pro Max Simulator"
          - "iPhone 12 Pro Simulator"
      fail-fast: false
    runs-on: macos-latest
    needs: test
    steps:
      - name: List all simulators
        run: xcrun xctrace list devices
      # get UUID  simulator and boot a simulator on mac from  command line
      - name: Start Simulator
        run: |
          UDID=$(xcrun xctrace list devices | awk '!/Watch/ && /${{ matrix.device }}/{gsub( /\(|\)/ , "" );print $NF}')
          xcrun simctl boot ${UDID}
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      # Run flutter integrate tests
      - name: Run Flutter Driver tests
        run: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart
        #screenshot
      - name: upload screenshot
        uses: actions/upload-artifact@master
          with:
            name: screenshot_${{ matrix.device }}
            path: /tmp/iwfpapp_screenshot

  drive_android:
    runs-on: macos-latest
    #creates a build matrix for your jobs
    strategy:
      #set of different configurations of the virtual environment.
      matrix:
        api-level: [31]
        target: [default]
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Run Flutter Driver tests
        uses: reactivecircus/android-emulator-runner@v1
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus 6
          script: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/app_test.dart