name: Run unit tests

on:
  push:
    branches:
      - '*'

jobs:
  run-tests:
    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@task/19-initialize_mnemonic
    with:
      e2e: false
