name: Run e2e tests in all infrastructure branches

on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

jobs:
  run-tests:
#    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@41_IntegrationTests_Mario
    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@$${GITHUB_REF##*/}
    with:
      e2e: true
      unitTests: false