name: Run e2e tests in all infrastructure branches

on:
  push:
    branches:
      - 'infrastructure/**'
      - '\S*Mario'
  workflow_dispatch:

jobs:
  run-tests:
    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@IntegrationTests_gherkin_imp_Mario
    with:
      e2e: true
      unitTests: false
