name: Run unit tests

on:
  push:
    branches:
      - '*'

jobs:
  run-tests:
    uses: SimplioOfficial/simplio-app/.github/workflows/run_integration_tests.yml@feature/initial-infrastructure
    with:
      e2e: false
