name: Run api tests

on:
  push:
    branches:
      - '*'
jobs:
  run-tests:
    uses: SimplioOfficial/simplio-app/.github/workflows/_api_tests.yml@insfrastructure/apiTests_Mario
    with:
      api-tests: true
