name: Run e2e tests in all infrastructure branches

on:
  push:
    branches:
      - 'infrastructure/**'
  workflow_dispatch:

jobs:
  set-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
      - name: Test
        run: echo "${BRANCH_NAME}"
  run-tests:
#    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@infrastructure/11_init_test
    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@${{github.ref}}
    with:
      e2e: true
      unitTests: false
