name: Run unit tests

on:
  push:
    branches:
      - '*'

jobs:
  run-tests:
    uses: SimplioOfficial/simplio-app/.github/workflows/_test_application.yml@subtask/11-automatic_version_increase
    with:
      e2e: false
